# Generated by Django 5.1.6 on 2025-02-27 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話')),
                ('is_admin', models.BooleanField(default=False, verbose_name='管理員權限')),
                ('is_designer', models.BooleanField(default=False, verbose_name='設計師權限')),
                ('is_project_manager', models.BooleanField(default=False, verbose_name='專案管理權限')),
                ('can_request_payment', models.BooleanField(default=False, verbose_name='請款權限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者檔案',
                'verbose_name_plural': '使用者檔案',
            },
        ),
    ]
