# Generated by Django 5.1.6 on 2025-02-27 05:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="tax_id",
            field=models.CharField(default="83387036", max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
