# Generated by Django 5.1.6 on 2025-03-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_project_change_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
