# Generated by Django 5.1.6 on 2025-04-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_payment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='custom_field_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='projectchange',
            name='created_at',
            field=models.DateField(),
        ),
    ]
