# Generated by Django 5.1.6 on 2025-04-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_category_custom_field_schema_project_custom_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='drawing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
