# Generated by Django 5.1.6 on 2025-04-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_project_drawing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='drawing_other',
        ),
        migrations.AddField(
            model_name='project',
            name='report_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
