# Generated by Django 5.1.6 on 2025-04-21 06:54

from django.conf import settings
from django.db import migrations, models


def migrate_manager_data(apps, schema_editor):
    Project = apps.get_model("crm", "Project")
    for project in Project.objects.all():
        if project.manager:  # 如果原本有設定專案負責人
            project.managers.add(project.manager)  # 加入到多對多關係中


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0011_remove_project_drawing_other_project_report_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                related_name="managed_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="專案負責人",
            ),
        ),
        migrations.RunPython(migrate_manager_data),
        migrations.RemoveField(
            model_name="project",
            name="manager",
        ),
    ]
