# Generated by Django 5.1.6 on 2025-05-20 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_remove_project_manager_project_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('responsible_person', models.CharField(max_length=255)),
                ('tax_id', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_person', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='account_entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='actual_received_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', '現金'), ('bank_transfer', '銀行轉帳'), ('check', '支票'), ('credit_card', '信用卡'), ('other', '其他')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_code', models.CharField(max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='crm.company')),
            ],
            options={
                'unique_together': {('company', 'account_number')},
            },
        ),
    ]
