# Generated by Django 5.1.6 on 2025-05-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_company_invoice_account_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='actual_received_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentproject',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_expenditure',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
