# Generated by Django 5.1.6 on 2025-05-23 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_payment_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='selected_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='crm.bankaccount'),
        ),
    ]
