# Generated by Django 5.1.6 on 2025-08-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_owner_phone_alter_project_project_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='fax',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
