# Generated by Django 5.1.6 on 2025-08-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_invoice_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('normal', '正常開立'), ('no_invoice', '不開發票'), ('pending', '發票待開')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('paid', '已付款'), ('unpaid', '未付款'), ('partially_paid', '付款未完成')], default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
    ]
