# Generated by Django 5.1.6 on 2025-08-20 06:36

from django.db import migrations


def update_payment_status(apps, schema_editor):
    """將現有發票的is_paid欄位資料轉換到payment_status欄位"""
    Invoice = apps.get_model('crm', 'Invoice')
    
    # 更新現有發票的payment_status
    for invoice in Invoice.objects.all():
        if invoice.is_paid:
            invoice.payment_status = 'paid'
        else:
            invoice.payment_status = 'unpaid'
        invoice.save(update_fields=['payment_status'])


def reverse_payment_status(apps, schema_editor):
    """回滾操作：從payment_status回到is_paid"""
    Invoice = apps.get_model('crm', 'Invoice')
    
    for invoice in Invoice.objects.all():
        invoice.is_paid = (invoice.payment_status == 'paid')
        invoice.save(update_fields=['is_paid'])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_invoice_invoice_type_invoice_payment_status_and_more'),
    ]

    operations = [
        migrations.RunPython(update_payment_status, reverse_payment_status),
    ]
