# Generated by Django 5.1.6 on 2025-09-01 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_auto_20250820_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.invoice')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.project')),
            ],
            options={
                'unique_together': {('invoice', 'project')},
            },
        ),
    ]
