# Generated by Django 5.1.6 on 2025-09-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_projectinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvoice',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
