# Generated by Django 5.1.6 on 2025-09-08 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_projectinvoice_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', '現金'), ('bank_transfer', '銀行轉帳'), ('check', '支票'), ('credit_card', '信用卡'), ('other', '其他')], max_length=20, null=True)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.payment')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.project')),
            ],
        ),
    ]
