# Generated by Django 5.1.6 on 2025-09-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_projectpayment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectPayment',
            new_name='ProjectReceipt',
        ),
    ]
