# Generated by Django 5.1.6 on 2025-09-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_rename_projectpayment_projectreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
