# Generated by Django 5.1.6 on 2025-09-19 07:43

from django.db import migrations


def remove_misc_project_from_all_payments(apps, schema_editor):
    """
    從所有請款單中移除「其他」專案關聯記錄
    """
    Project = apps.get_model('crm', 'Project')
    PaymentProject = apps.get_model('crm', 'PaymentProject')
    Category = apps.get_model('crm', 'Category')
    
    try:
        # 取得「其他」專案
        category = Category.objects.get(code='OTHER')
        misc_project = Project.objects.get(
            name='其他',
            category=category,
            project_number='9999'
        )
        
        # 移除所有包含「其他」專案的 PaymentProject 記錄
        deleted_count = PaymentProject.objects.filter(project=misc_project).count()
        PaymentProject.objects.filter(project=misc_project).delete()
        
        print(f"成功從 {deleted_count} 個請款單中移除「其他」專案")
        
    except (Category.DoesNotExist, Project.DoesNotExist):
        print("找不到「其他」專案，跳過移除操作")


def restore_misc_project_to_payments(apps, schema_editor):
    """
    反向操作：將「其他」專案重新加回到所有請款單中
    """
    Project = apps.get_model('crm', 'Project')
    Payment = apps.get_model('crm', 'Payment')
    PaymentProject = apps.get_model('crm', 'PaymentProject')
    Category = apps.get_model('crm', 'Category')
    
    try:
        # 取得「其他」專案
        category = Category.objects.get(code='OTHER')
        misc_project = Project.objects.get(
            name='其他',
            category=category,
            project_number='9999'
        )
        
        # 取得所有既有的請款單
        existing_payments = Payment.objects.all()
        
        created_count = 0
        for payment in existing_payments:
            # 檢查該請款單是否已經有「其他」專案
            existing_misc = PaymentProject.objects.filter(
                payment=payment,
                project=misc_project
            ).exists()
            
            if not existing_misc:
                # 新增「其他」專案到請款單中，預設金額為 0
                PaymentProject.objects.create(
                    payment=payment,
                    project=misc_project,
                    amount=0,
                    description='雜費項目（影印費、郵資費等）'
                )
                created_count += 1
        
        print(f"成功將「其他」專案重新加入到 {created_count} 個請款單中")
        
    except (Category.DoesNotExist, Project.DoesNotExist):
        print("找不到「其他」專案，跳過重新加入操作")


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_add_misc_project'),
    ]

    operations = [
        migrations.RunPython(
            remove_misc_project_from_all_payments,
            reverse_code=restore_misc_project_to_payments,
            atomic=True
        ),
    ]
