# Generated by Django 5.1.6 on 2025-09-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_remove_misc_project_from_existing_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='quoted_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
