# Generated by Django 5.1.6 on 2025-12-08 01:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_project_quoted_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='supervised_projects', to=settings.AUTH_USER_MODEL, verbose_name='監造人員'),
        ),
    ]
