# Generated by Django 5.1.6 on 2025-12-09 03:30

from django.db import migrations, models


def migrate_is_completed_to_status(apps, schema_editor):
    """將現有的 is_completed 資料轉換為 status"""
    Project = apps.get_model('crm', 'Project')
    # 將已完成的專案設為 'completed'
    Project.objects.filter(is_completed=True).update(status='completed')
    # 將未完成的專案設為 'in_progress'
    Project.objects.filter(is_completed=False).update(status='in_progress')


def reverse_migrate_status_to_is_completed(apps, schema_editor):
    """回滾時將 status 轉換回 is_completed"""
    Project = apps.get_model('crm', 'Project')
    # 將 completed 狀態設為已完成
    Project.objects.filter(status='completed').update(is_completed=True)
    # 將其他狀態設為未完成
    Project.objects.exclude(status='completed').update(is_completed=False)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_project_supervisors'),
    ]

    operations = [
        # 1. 新增 status 欄位
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(
                choices=[
                    ('in_progress', '進行中'),
                    ('paused', '暫停'),
                    ('completed', '已完成'),
                    ('cancelled', '撤案'),
                ],
                default='in_progress',
                max_length=20,
                verbose_name='專案狀態'
            ),
        ),
        # 2. 遷移資料
        migrations.RunPython(
            migrate_is_completed_to_status,
            reverse_migrate_status_to_is_completed
        ),
    ]
