# Generated by manual creation

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_add_project_status_field'),
    ]

    operations = [
        # 移除 is_completed 欄位，因為已經改用 status + @property
        migrations.RemoveField(
            model_name='project',
            name='is_completed',
        ),
    ]
