# Generated by Django 5.1.6 on 2026-01-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_remove_is_completed_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='enforce_three_digit_number',
            field=models.BooleanField(default=True, help_text='若啟用，此類別的專案編號必須為三位數字 (001-999)', verbose_name='限制三位數字編號'),
        ),
    ]
