# Generated by Django 5.1.6 on 2026-01-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_category_enforce_three_digit_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method_note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectreceipt',
            name='payment_method_note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
